
# Server configs
server.port=7000
server.servlet.context-path=/studio-service
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=health,info,heapdump,shutdown,loggers
management.security.enabled= false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method

# Spring configs
spring.batch.job.enabled=false
spring.profiles.active=local
spring.security.enabled=false

# MySQL configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/live?autoreconnect=true
spring.datasource.username=root
spring.datasource.password=

# Additional optional configurations for better performance
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.housekeeping-period-ms=600000

# Hibernate Configs
spring.jpa.show-sql= true
spring.jpa.generate-ddl= true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Cache configuration
spring.cache.type=simple

# S3 Configs
aws.s3.bucket-name=book-and-manage-invoices
aws.region.static=ap-south-1
aws.access-key=AKIA6Q3AXO2TPD7STSYK
aws.secret-key=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

# Cloudinary
cloudinary.cloud_name=dvraa4zpz
cloudinary.api_key=369423993223831
cloudinary.api_secret=NJ-btV2ZSClsfxsGrkv-KKFSUh4

# JWT configuration
jwt.secret=E9jdAFJv8umSwIu3a/ynKNQ/1LSZjdHl6WGzGseFmS3mkWtt2Vkv27C5US1Qdod0yIX4NdBgy4d+HeP56xaCWA==
jwt.auth.expiration.ms=30000000
jwt.refresh.expiration.ms=300000000
jwt.otp.expiration.ms=30000000

# mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bookandmanage@gmail.com
spring.mail.password=mibs pype ickx pavk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.debug=true

# Razorpay
razorpay.api_key=rzp_test_T1tukRjY2DAGda
razorpay.api_secret=PuWkYEOoP1KgQV0tTyF7vBC4

ultramsg.api.url=https://api.ultramsg.com
create.session.url=http://localhost:5002

# clean up service
cleanup.cron=0 0 3 * * ?